import {
    FrameworkType,
    DatabaseType,
    ApiPatternType,
    LanguageType,
    StylingType,
    AnimationType,
} from "./types";

export const FREE_STACKS = {
    framework: ["None", "React", "Next.js", "Express"] as FrameworkType[],
    database: ["None", "MongoDB", "PostgreSQL"] as DatabaseType[],
    apiPattern: ["None", "REST", "Server Actions"] as ApiPatternType[],
    language: ["TypeScript", "JavaScript"] as LanguageType[],
    styling: ["Tailwind CSS", "shadcn/ui"] as StylingType[],
    animation: ["Framer Motion", "None"] as AnimationType[],
};

export interface StackOption {
    name: string;
    category: string;
    isPopular?: boolean;
}

export const ALL_STACKS: Record<string, StackOption[]> = {
    framework: [
        { name: "None", category: "General", isPopular: true },
        // Frontend
        { name: "Next.js", category: "Frontend", isPopular: true },
        { name: "React", category: "Frontend", isPopular: true },
        { name: "Vue", category: "Frontend" },
        { name: "Vue 3 (Composition)", category: "Frontend" },
        { name: "Svelte", category: "Frontend" },
        { name: "SvelteKit", category: "Frontend" },
        { name: "Nuxt", category: "Frontend" },
        { name: "Gatsby", category: "Frontend" },
        { name: "Remix", category: "Frontend" },
        { name: "Astro", category: "Frontend" },
        { name: "Solid.js", category: "Frontend" },
        { name: "Qwik", category: "Frontend" },
        // Backend
        { name: "Express", category: "Backend", isPopular: true },
        { name: "NestJS", category: "Backend" },
        { name: "FastAPI", category: "Backend" },
        { name: "Django", category: "Backend" },
        { name: "Flask", category: "Backend" },
        { name: "Spring Boot", category: "Backend" },
        { name: "Laravel", category: "Backend" },
        { name: "Ruby on Rails", category: "Backend" },
        { name: "Phoenix (Elixir)", category: "Backend" },
        { name: "AdonisJS", category: "Backend" },
        // Mobile
        { name: "React Native", category: "Mobile" },
        { name: "Flutter", category: "Mobile" },
        { name: "SwiftUI", category: "Mobile" },
        { name: "Jetpack Compose", category: "Mobile" },
        { name: "Expo", category: "Mobile" },
        // Desktop
        { name: "Electron", category: "Desktop" },
        { name: "Tauri", category: "Desktop" },
        // Fullstack
        { name: "RedwoodJS", category: "Fullstack" },
        { name: "Blitz.js", category: "Fullstack" },
    ],
    database: [
        { name: "None", category: "General", isPopular: true },
        { name: "PostgreSQL", category: "SQL", isPopular: true },
        { name: "MySQL", category: "SQL" },
        { name: "MariaDB", category: "SQL" },
        { name: "MongoDB", category: "NoSQL", isPopular: true },
        { name: "SQLite", category: "Local" },
        { name: "Redis", category: "KV/Cache", isPopular: true },
        { name: "Supabase", category: "Managed", isPopular: true },
        { name: "PlanetScale", category: "SQL" },
        { name: "Neon", category: "SQL" },
        { name: "SurrealDB", category: "Multi" },
        { name: "Pinecone", category: "Vector" },
        { name: "Weaviate", category: "Vector" },
        { name: "Qdrant", category: "Vector" },
        { name: "Cassandra", category: "NoSQL" },
        { name: "DynamoDB", category: "NoSQL" },
        { name: "Firebase Firestore", category: "NoSQL" },
        { name: "Prisma", category: "ORM", isPopular: true },
        { name: "Drizzle", category: "ORM" },
        { name: "Convex", category: "Managed" },
    ],
    apiPattern: [
        { name: "None", category: "General", isPopular: true },
        { name: "REST", category: "Legacy/Standard", isPopular: true },
        { name: "GraphQL", category: "Flexible", isPopular: true },
        { name: "tRPC", category: "Type-Safe", isPopular: true },
        { name: "gRPC", category: "Microservices" },
        { name: "WebSockets", category: "Real-time" },
        { name: "Server Actions", category: "Modern", isPopular: true },
        { name: "Server Components", category: "Modern" },
        { name: "Falcor", category: "Graph" },
        { name: "OData", category: "Searchable" },
        { name: "SOAP", category: "Enterprise" },
        { name: "Pub/Sub", category: "Messaging" },
        { name: "Kafka Streams", category: "Data" },
    ],
    language: [
        { name: "TypeScript", category: "Strict", isPopular: true },
        { name: "JavaScript", category: "Dynamic", isPopular: true },
        { name: "Python", category: "Scripts/AI", isPopular: true },
        { name: "Go", category: "Systems" },
        { name: "Java", category: "Enterprise" },
        { name: "Kotlin", category: "Mobile" },
        { name: "Swift", category: "Apple" },
        { name: "Dart", category: "Google" },
        { name: "C#", category: "Gaming/MS" },
        { name: "Rust", category: "Performance" },
        { name: "PHP", category: "Web" },
        { name: "Ruby", category: "Web" },
        { name: "Elixir", category: "Concurrent" },
        { name: "Scala", category: "Functional" },
        { name: "Zig", category: "Modern" },
        { name: "Crystal", category: "Modern" },
        { name: "Nim", category: "Modern" },
    ],
    styling: [
        { name: "Tailwind CSS", category: "Utility", isPopular: true },
        { name: "shadcn/ui", category: "Components", isPopular: true },
        { name: "Chakra UI", category: "React-Only" },
        { name: "Material UI", category: "Enterprise" },
        { name: "Ant Design", category: "Enterprise" },
        { name: "Mantine", category: "Flexible" },
        { name: "Radix UI", category: "Headless" },
        { name: "Headless UI", category: "Headless" },
        { name: "CSS Modules", category: "Isolation" },
        { name: "Styled Components", category: "CSS-in-JS" },
        { name: "Emotion", category: "CSS-in-JS" },
        { name: "Stitches", category: "CSS-in-JS" },
        { name: "Vanilla Extract", category: "Modern" },
        { name: "NativeWind", category: "Mobile" },
        { name: "SwiftUI", category: "Apple" },
        { name: "Jetpack Compose", category: "Android" },
        { name: "Flutter Material", category: "Google" },
        { name: "Bootstrap", category: "Classic" },
        { name: "Bulma", category: "Classic" },
        { name: "Pico CSS", category: "Minimal" },
        { name: "CSS-in-JS", category: "General" },
    ],
    animation: [
        { name: "Framer Motion", category: "High Performance", isPopular: true },
        { name: "React Spring", category: "Physics" },
        { name: "GSAP", category: "Power User" },
        { name: "Three.js", category: "3D/Web GL" },
        { name: "Lottie", category: "Assets" },
        { name: "Remotion", category: "Video" },
        { name: "Reanimated", category: "Mobile" },
        { name: "Motion One", category: "Lightweight" },
        { name: "Anime.js", category: "Compact" },
        { name: "Popmotion", category: "Low-level" },
        { name: "CSS Keyframes", category: "Native" },
        { name: "CSS Transitions", category: "Native" },
        { name: "View Transitions API", category: "Browser Premium" },
        { name: "Web Animations API", category: "Browser Native" },
        { name: "Spline", category: "3D" },
        { name: "Rive", category: "Interactive" },
        { name: "LottieFiles", category: "Marketplace" },
        { name: "None", category: "Clean", isPopular: true },
    ],
};
