export const pricingTiers = [
    {
        id: "free",
        name: "Free",
        price: "₹0",
        priceNumeric: 0,
        description: "Perfect for testing the waters and small personal projects.",
        features: [
            "5 prompts per month",
            "Fast & Responsive UI",
            "Dynamic Goal Modes & Health Hints",
            "Target Model Personas (Claude, ChatGPT, etc.)",
            "Local history storage (up to 10)",
            "Essential web stacks (React, Express, Postgres)",
            "Same core CO-STAR prompt quality",
            "Standard Support",
        ],
        isPopular: false,
    },
    {
        id: "pro_monthly",
        name: "Pro",
        price: "₹149",
        priceNumeric: 149,
        razorpay_plan_id: process.env.NEXT_PUBLIC_RAZORPAY_PRO_PLAN_ID,
        description: "The sweet spot for active developers and prompt engineers.",
        features: [
            "Unlimited prompts each month",
            "1-Click 'Prompt Recipes' & Templates",
            "All Backend/Frontend Stacks Unlocked",
            "Opinionated Engineering Defaults (Strict JS, a11y, etc.)",
            "Cloud-synced History with Tags & Search",
            "Autopay Billing (GPay, PhonePe, Cards)",
            "Flexible Cancellation (Keep access until period ends)",
            "Priority Support",
        ],
        isPopular: true,
    },
    {
        id: "test_plan",
        name: "Pro",
        price: "₹1",
        priceNumeric: 1,
        razorpay_plan_id: process.env.NEXT_PUBLIC_RAZORPAY_PRO_PLAN_ID,
        description: "The sweet spot for active developers and prompt engineers.",
        features: [
            "Unlimited prompts each month",
            "1-Click 'Prompt Recipes' & Templates",
            "All Backend/Frontend Stacks Unlocked",
            "Opinionated Engineering Defaults (Strict JS, a11y, etc.)",
            "Cloud-synced History with Tags & Search",
            "Autopay Billing (GPay, PhonePe, Cards)",
            "Flexible Cancellation (Keep access until period ends)",
            "Priority Support",
        ],
        isPopular: true,
    }
    // {
    //     id: "lifetime",
    //     name: "Lifetime",
    //     price: "₹4999",
    //     priceNumeric: 4999,
    //     description: "One-time investment for eternal creative freedom.",
    //     features: [
    //         "Everything in Pro plan",
    //         "Pay once, use forever",
    //         "Early access to new features",
    //         "Limited: First 10 users only",
    //         "Free updates forever",
    //     ],
    //     isPopular: false,
    // },
];
