export const pricingTiers = [
    {
        id: "free",
        name: "Free",
        price: "₹0",
        priceNumeric: 0,
        description: "Perfect for testing the waters and small personal projects.",
        features: [
            "5 prompts per month",
            "Dynamic Goal Modes & Health Hints",
            "Target Model Personas (Claude, ChatGPT, etc.)",
            "Local history storage (up to 10)",
            "Essential web stacks (React, Express, Postgres)",
            "Same core CO-STAR prompt quality",
        ],
        isPopular: false,
    },
    {
        id: "pro_monthly",
        name: "Pro",
        price: "₹149",
        priceNumeric: 149,
        description: "The sweet spot for active developers and prompt engineers.",
        features: [
            "Unlimited prompts each month",
            "1-Click 'Prompt Recipes' & Templates",
            "Opinionated Engineering Defaults (Strict JS, a11y, etc.)",
            "Cloud-synced History with Tags & Search",
            "All Backend/Frontend Stacks Unlocked",
            "Export to DOC & Usage Dashboard",
        ],
        isPopular: true,
    },
    // {
    //     id: "lifetime",
    //     name: "Lifetime",
    //     price: "₹4999",
    //     priceNumeric: 4999,
    //     description: "One-time investment for eternal creative freedom.",
    //     features: [
    //         "Everything in Pro plan",
    //         "Pay once, use forever",
    //         "Early access to new features",
    //         "Limited: First 10 users only",
    //         "Free updates forever",
    //     ],
    //     isPopular: false,
    // },
];
