export const pricingTiers = [
    {
        id: "free",
        name: "Free",
        price: "₹0",
        priceNumeric: 0,
        description: "Perfect for testing the waters and small personal projects.",
        features: [
            "5 total prompts / month (After trial)",
            "Magic 5 Trial: 3 Guest + 2 Auth Pro prompts",
            "Essential web stacks (React, Express, Postgres)",
            "Smart Stack Inference (Auto-detect AI)",
            "Basic Target AI Personas (Open-Source Llama, etc.)",
            "Standard Goal Modes (Scaffold, Production)",
            "Local history storage (up to 10)",
        ],
        isPopular: false,
    },
    {
        id: "pro_monthly",
        name: "Pro",
        price: "₹149",
        priceNumeric: 149,
        razorpay_plan_id: process.env.NEXT_PUBLIC_RAZORPAY_PRO_PLAN_ID,
        description: "The sweet spot for active developers and prompt engineers.",
        features: [
            "Unlimited prompts each month",
            "Interactive Agentic Dashboard (Live Flight Plans)",
            "Advanced AI & IDE Personas (Antigravity, Claude, Cursor)",
            "Architecture Guardrails (Blueprint Presets & Standards)",
            "Premium Goal Modes (Refactor, Debug, SEO, a11y)",
            "Full Stack Control (All Stacks & Deployments Unlocked)",
            "Cloud-synced History with Tags & Search",
            "Priority Support",
        ],
        isPopular: true,
    },
    
    // {
    //     id: "lifetime",
    //     name: "Lifetime",
    //     price: "₹4999",
    //     priceNumeric: 4999,
    //     description: "One-time investment for eternal creative freedom.",
    //     features: [
    //         "Everything in Pro plan",
    //         "Pay once, use forever",
    //         "Early access to new features",
    //         "Limited: First 10 users only",
    //         "Free updates forever",
    //     ],
    //     isPopular: false,
    // },
];
